"PyQt5 Migrated"
omi10859/jarvis pull request #23
Opened 2019-03-04 13:31 UTC by iamchiragsharma

- Switched the UI from Tkinter to PyQT5.
- Fixed The Microphone Sound Issue and Getting control back from the Gui.(Issue #22)
- Groot Doesn't Crash Now. (Issue #21)

**Please do python base.py instead of python Gui.py. Since PyQt5 works best with Object Oriented Programming we had to dedicate it a file and Gui named fitted best.**
Installed the dependencies it shows.

**This pull is done by myself(@iamchiragsharma) and @nikhilmehta011.**

2019-03-04 13:35 UTC, omi10859 commented
Please add Screenshot/Gif

2019-03-04 15:16 UTC, iamchiragsharma commented
- Quit Confirmation is also Added.
- Type python base.py (Terminal).
- Groot Crashing Resolved.

![issue23](https://user-images.githubusercontent.com/29746593/53742363-7b9b6280-3ebe-11e9-9117-851d3d1e5d1c.gif)

2019-03-04 16:32 UTC, lalitmee requested changes

2019-03-04 16:32 UTC, lalitmee commented on Gui.py
> +        self.inpEdit = QLineEdit()  #Text Field for Input
Can we put the comments docs above the lines not in the lines?

2019-03-04 16:49 UTC, iamchiragsharma commented
Yes we can. i will do it tomorrow after exam, is that okay?

2019-03-04 17:04 UTC, lalitmee commented
Yeah, sure.

2019-03-04 17:44 UTC, iamchiragsharma commented
Done. Please take a look.

2019-03-05 11:27 UTC, techytushar reviewed
You might also need to update the `requirements` file

2019-03-05 17:02 UTC, lalitmee requested changes

2019-03-05 17:02 UTC, lalitmee commented on Gui.py
> +        #When the Speak button is clicked the listen function is triggered.
This should go above the line number `46` because this is for that line. :thinking:

2019-03-07 11:59 UTC, omi10859 approved these changes

2019-03-07 15:18 UTC, merged